name: Trigger auto deployment for java-test-3

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/java-test-3-AutoDeployTrigger-ae153659-3956-4d93-9d8f-fea250bd483f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.JAVATEST3_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.JAVATEST3_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.JAVATEST3_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.JAVATEST3_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.JAVATEST3_REGISTRY_PASSWORD }}
          containerAppName: java-test-3
          resourceGroup: javaTesting
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


