name: Trigger auto deployment for oidcapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/oidcapp-AutoDeployTrigger-c7b0fb60-028b-4dd9-8873-b58b9289c184.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.OIDCAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: testoidcreg1.azurecr.io
          registryUsername: ${{ secrets.OIDCAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OIDCAPP_REGISTRY_PASSWORD }}
          containerAppName: oidcapp
          resourceGroup: Testing
          imageToBuild: testoidcreg1.azurecr.io/oidcapp:${{ github.sha }}
          

     

