name: Trigger auto deployment for principal-testing

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/principal-testing-AutoDeployTrigger-42f0742b-9d82-470e-8257-3d1822954371.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PRINCIPALTESTING_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: testreg15.azurecr.io
          registryUsername: ${{ secrets.PRINCIPALTESTING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PRINCIPALTESTING_REGISTRY_PASSWORD }}
          containerAppName: principal-testing
          resourceGroup: DefaultResourceGroup-CCAN
          imageToBuild: testreg15.azurecr.io/principal-testing:${{ github.sha }}
          
            

     

